### ISSUE TITLE
Add proper source code

### ISSUE THREAD

**Issue by GingerGigiCat** [araafroyall/Cleaner-Royall#33]
### Bug Submission

I don't know why github decided to suggest this repo to me, but it's really dodgy. You can't just replace all your source code with "The Project is Private" (https://github.com/araafroyall/Cleaner-Royall/commit/d1c7537b5a57943d72a5d5fc372c32506a5da8df) and looking at the commit history, this doesn't actually do any cleaning. 
Oh, and that https://github.com/araafroyall/Cleaner-Royall/blob/main/app/NOTICE says that the source code doesn't contain any cleaning, but the notice file was uploaded two months after the source code was in the first place.
You also don't say in the readme what this project cleans, so I'd suggest you add that.

This isn't how open source software works, you can't just hide the code that actually does things.
Please fix it, or just don't have it on github

### Android Version

Android 13

**Comment by GingerGigiCat** [comment]
Also, "No Permission Required (Except Root)" is great

**Comment by araafroyall** [comment]
> Also, "No Permission Required (Except Root)" is great

I understands. Source code is just remove for some days as i have changed package name recently , so i may reupload them

but Cleaning codes will be kept private to prevent misuse.. if you have any other question feel free to ask.

Also Note that this is most powerful cleaner ever made , you can read all features details in the app

**Comment by GingerGigiCat** [comment]
Surely it takes way too much effort to filter through the code to remove the cleaning code before uploading it? And what type of misuse would hiding the cleaning code prevent?

Most people don't want to install the app to find out all the features

**Comment by araafroyall** [comment]
> Surely it takes way too much effort to filter through the code to remove the cleaning code before uploading it? And what type of misuse would hiding the cleaning code prevent?
> 
> Most people don't want to install the app to find out all the features

I made this project with very hard work under 1mb with no permission requested with powerful cleaning mechanism including Systemless module.

if i will make its cleaning code publicly than most developer will copy this than what will be the use of my app.
and i want my app remain paid.

Main features are listed on readme and i will update that soon with all features Listing.

**Comment by araafroyall** [comment]
![Screenshot_2024-08-08-20-38-16-694_Cleaner.Royall.png](https://github.com/user-attachments/assets/b33c1cd1-6336-4be5-8ce7-77e5ee321b50)

Here are 1 feature explained for cleaning . 
I made thousands of such features in the app.
and will be posted soon in readme

**Comment by GingerGigiCat** [comment]
I understand that you don't want to release the source code if your app is paid, but then what's the point of having the partially hidden source code on github?

**Comment by araafroyall** [comment]
> I understand that you don't want to release the source code if your app is paid, but then what's the point of having the partially hidden source code on github?


I will provide partially code except cleaning one for people that app is 100% safe and secure so anyone can see its structure.
hope you understand 👍

**Comment by GingerGigiCat** [comment]
But if you're hiding some of the code how will people know that the code you are hiding is safe?

**Comment by araafroyall** [comment]
> But if you're hiding some of the code how will people know that the code you are hiding is safe?

App cleaning codes is 100% safe 

So what do you think what other work can cleaning mechanism do other than cleaning.

**Comment by GingerGigiCat** [comment]
It could be doing something malicious, but I don't know because I can't see the full code

**Comment by araafroyall** [comment]
> It could be doing something malicious, but I don't know because I can't see the full code

It do nothing malicious.

ok i have a solution. 
First try this app in a virtual ROM like Vmos .

And in any condition i will not provide cleaning code hope you understand. 

Also many people are already using my app 
and i am Responsible for this app 100% that app is safe and secure not even collects single word.


Why you not try first in a virtual ROM ?

**Comment by GingerGigiCat** [comment]
I don't have a virtual ROM to test it in. Also I thought you said the app is paid?

**Comment by araafroyall** [comment]
> I don't have a virtual ROM to test it in. Also I thought you said the app is paid?

There are some Free features too , have a try

If you understand 👍 Please close this issue ok

**Comment by araafroyall** [comment]
> Then why not make the source code of the free features available? I'm sure that would make future potential users happier about using the app


Thanks for suggesting. i will look upon this 

or i will make a lite version for free usage with all source code

**Comment by GingerGigiCat** [comment]
That sounds like a good idea. I'll be waiting for it

**Comment by araafroyall** [comment]
> That sounds like a good idea. I'll be waiting for it

Ok.

**Comment by GingerGigiCat** [comment]
It's not fixed yet, you can't mark it as completed

**Comment by araafroyall** [comment]
> It's not fixed yet, you can't mark it as completed

Ok than change its title , i dont like that. 

Keep opened 👍👍
