### ISSUE TITLE
Missing source code

### ISSUE THREAD

**Issue by GingerGigiCat** [araafroyall/Cleaner-Royall#34]
### Bug Submission

(See https://github.com/araafroyall/Cleaner-Royall/issues/33)
After coming to the agreement that source code will be included in the future, you reopened my previous issue so that it can be closed when source code is added. But you just closed the issue as "Not planned".

Currently your repository is very misleading as it appears to have the source code at first glance, but all that the files contain is "The project is private".

Please leave this ticket open until you add source code.

### Android Version

Android 13

**Comment by araafroyall** [comment]
Ok. Sure 👍👍

**Comment by araafroyall** [comment]
> ### Bug Submission
> 
> (See https://github.com/araafroyall/Cleaner-Royall/issues/33)
> After coming to the agreement that source code will be included in the future, you reopened my previous issue so that it can be closed when source code is added. But you just closed the issue as "Not planned".
> 
> Currently your repository is very misleading as it appears to have the source code at first glance, but all that the files contain is "The project is private".
> 
> Please leave this ticket open until you add source code.
> 
> ### Android Version
> 
> Android 13
> 
> ### Comments or Extra Info
> 
> _No response_
> 
> ### App Version
> 
> _No response_

The main problem is that i have started my study and i dont have enough time for uploading source code , so wait and keep open this issue for 1 year .

**Comment by araafroyall** [comment]
> ### Bug Submission
> 
> (See https://github.com/araafroyall/Cleaner-Royall/issues/33)
> After coming to the agreement that source code will be included in the future, you reopened my previous issue so that it can be closed when source code is added. But you just closed the issue as "Not planned".
> 
> Currently your repository is very misleading as it appears to have the source code at first glance, but all that the files contain is "The project is private".
> 
> Please leave this ticket open until you add source code.
> 
> ### Android Version
> 
> Android 13
> 
> ### Comments or Extra Info
> 
> _No response_
> 
> ### App Version
> 
> _No response_

Source code is now available , Check ✅

**Comment by ICyperior** [comment]
It's Missing source code.

Just updating some strings every like 1 hour.

**Comment by araafroyall** [comment]
> It's Missing source code.
> 
> Just updating some strings every like 1 hour.

have you not seen All source code are available.

and those string are server related , i am making an online cleaning feature from that string. for v3.7
when the version release you can check that

**Comment by araafroyall** [comment]
> It's Missing source code.
> 
> Just updating some strings every like 1 hour.

Brother .
i cant provide full app update everytime so i making a server related feature , which is fully open source (you can view in server folder of this repo)

it will help in viewing old changelog , upcoming features 
custom cleaner , smart cleaner , auto activation of premium version

and its currently in development 

so just tell me yourself what missing in source code.

**Comment by araafroyall** [comment]
@araafroyall New Hot Feature 🔥
