### ISSUE TITLE
License

### ISSUE THREAD

**Issue by shuvashish76** [araafroyall/Cleaner-Royall#35]
Hello, what's the license of this project?
related #33 #34

**Comment by araafroyall** [comment]
> Hello, what's the license of this project?
> related #33 #34

Hi freinds. 

Lisence and other stuff like source code will be available soon.

Please allow me upto 1 week to complete all these . 👍

**Comment by araafroyall** [comment]
> So it's not opensource. Okay thanks

No. i made with hard work and can't make it cleaning mechanism open source to prevent miss use .


I introduced premium features for that.
hope you understand 

but structure source code are open and uploaded
