### ISSUE TITLE
Missing Source Code (Currently Gibberish and Partial)

### ISSUE THREAD

**Issue by ICyperior** [araafroyall/Cleaner-Royall#39]
> ### Bug Submission
> 
> (See https://github.com/araafroyall/Cleaner-Royall/issues/33)
> After coming to the agreement that source code will be included in the future, you reopened my previous issue so that it can be closed when source code is added. But you just closed the issue as "Not planned".
> 
> Currently your repository is very misleading as it appears to have the source code at first glance, but all that the files contain is "The project is private".
> 
> Please leave this ticket open until you add source code.
> 
> ### Android Version
> 
> Android 14
> 
> ### Comments or Extra Info
> 
> _No response_
> 
> ### App Version
> 
> _No response_

Source code is now available , Check ✅

_Originally posted by @araafroyall in https://github.com/araafroyall/Cleaner-Royall/issues/34#issuecomment-2293647983_

**Comment by araafroyall** [comment]
>               > ### Bug Submission
> > 
> > (See https://github.com/araafroyall/Cleaner-Royall/issues/33)
> > After coming to the agreement that source code will be included in the future, you reopened my previous issue so that it can be closed when source code is added. But you just closed the issue as "Not planned".
> > 
> > Currently your repository is very misleading as it appears to have the source code at first glance, but all that the files contain is "The project is private".
> > 
> > Please leave this ticket open until you add source code.
> > 
> > ### Android Version
> > 
> > Android 14
> > 
> > ### Comments or Extra Info
> > 
> > _No response_
> > 
> > ### App Version
> > 
> > _No response_
> 
> Source code is now available , Check ✅
> 
> _Originally posted by @araafroyall in https://github.com/araafroyall/Cleaner-Royall/issues/34#issuecomment-2293647983_
>             

Tell me what missing in source code .

everything is available 
why you not check yourself
